### ISSUE TITLE
ZF2 bridge Bug - Cache factory can not return null

### ISSUE THREAD

**Issue by mmizera** [PHP-DI/ZF2-Bridge#11]
Hi

`DI\ZendFramework2\Service\Cache\CacheFactory` in `createService()` method can return null, but ZF2 ServiceLocator does not allow this behaviour - you'll get this :

```
\Zend\ServiceManager\ServiceManager @ 953
if ($instance === null) {
            throw new Exception\ServiceNotCreatedException('The factory was called but did not return an instance.');
        }
```

ZF2 version Im using is current stable ("zendframework/zendframework": "~2.5").

Proposed fixes : 
Add some 'BlackholeCache' as default service returned via DiCache factory
Or simple, but a little nasty - catch and handle ServiceNotCreatedException

**Comment by Rastusik** [comment]
I'll look into it this week, feel free to create a pull request yourself if you're in a hurry. But I would recommend another fix - https://github.com/PHP-DI/ZF2-Bridge/blob/master/src/DI/ZendFramework2/Service/DIContainerFactory.php#L62 - I would add a condition before the whole cache creation process, which would search for the 'cache' key in the configuration.

**Comment by Rastusik** [comment]
You are now able to omit the cache config.
