### ISSUE TITLE
Why can not I use several projects in one memcached instance?

### ISSUE THREAD

**Issue by MironowDW** [PHP-DI/ZF2-Bridge#16]
In README
> If you're using Memcached, you should have only one project per memcached instance.

But i can use namespace:
```php
return [
    'phpdi-zf2' => [
        'cache' => [
            'adapter' => 'memcached',
            'host' => 'localhost', // default is localhost
            'port' => 11211, // default is 11211
            'namespace' => 'my_second_project_',
        ],
    ]
];
```

**Comment by Rastusik** [comment]
well, possibly yes, but the MemcachedCache implementation doesn't support namespaces:

https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/MemcachedCache.php
