### ISSUE TITLE
PHP-DI should be aware of the "parent" ZF container

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/ZF2-Bridge#5]
```php
$builder->wrapContainer($serviceManager);
```

This means the service manager must implement DI\ContainerInterface, or we can wait for container-interop 1.0.

**Comment by Rastusik** [comment]
fixed in 4ac16fc5fd07969725765d65ca718d835ce26839

**Comment by Rastusik** [comment]
@mnapoli could you please configure packagist to make the new release? the package looks stable.

maybe it would be also useful to mention the package in the php-di docs :)

**Comment by mnapoli** [comment]
Hi! That's really great! I've enabled Travis for tests to run (https://travis-ci.org/PHP-DI/ZF2-Bridge).

Packagist is auto-updated, it seems to have picked up your new versions: https://packagist.org/packages/php-di/zf2-bridge

**Comment by mnapoli** [comment]
Also yes it would be great to document it. It would be great that the tests are green and up to date to document it on the main documentation. It helps guarantee to users that they get something working and that they won't get regressions in future versions.

Feel free to open a pull request on the main repository with docs, and maybe add the travis badge on this one and check that tests pass?

**Comment by mnapoli** [comment]
Oh it seems you are already working on tests ;) https://github.com/PHP-DI/ZF2-Bridge/releases/tag/1.0.3 Great!

**Comment by Rastusik** [comment]
yes, I just need to fing aout how set up the .travis.yaml file and then it's done :)

**Comment by mnapoli** [comment]
Good I see it's green now. I've opened a PR for composer config, feel free to merge it.
